"""updated task model

Revision ID: 483ff4896c4a
Revises: c20b75328f22
Create Date: 2026-06-30 10:16:10.846636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '483ff4896c4a'
down_revision: Union[str, Sequence[str], None] = 'c20b75328f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('tasks', sa.Column('tracking_token', sa.Uuid(), nullable=True))
    task_status_enum = postgresql.ENUM(
        "queued",
        "completed",
        "failed",
        name="taskstatus"
    )
    task_status_enum.create(op.get_bind())
    op.execute(
    """
    ALTER TABLE tasks
    ALTER COLUMN status
    TYPE taskstatus
    USING status::taskstatus
    """
)
    # op.alter_column('tasks', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Enum('queued', 'completed', 'failed', name='taskstatus'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('QUEUED', 'COMPLETED', 'FAILED', name='taskstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('tasks', 'tracking_token')
    op.drop_column('tasks', 'payload')
    # ### end Alembic commands ###
