"""add task history index

Revision ID: e05033625638
Revises: 688cec880795
Create Date: 2026-07-06 10:00:01.574591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05033625638'
down_revision: Union[str, Sequence[str], None] = '688cec880795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('task_user_id_created_at_idx', 'tasks', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('task_user_id_created_at_idx', table_name='tasks')
    # ### end Alembic commands ###
